//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ElComensal.ServiceSOAP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ComensalSOAPSoap", Namespace="http://tempuri.org/")]
    public partial class ComensalSOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listarLocalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarLocalOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarMesasOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarMesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarEstadoReservaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ComensalSOAP() {
            this.Url = global::ElComensal.Properties.Settings.Default.ElComensal_ServiceSOAP_ComensalSOAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listarLocalesCompletedEventHandler listarLocalesCompleted;
        
        /// <remarks/>
        public event registrarLocalCompletedEventHandler registrarLocalCompleted;
        
        /// <remarks/>
        public event listarMesasCompletedEventHandler listarMesasCompleted;
        
        /// <remarks/>
        public event registrarMesaCompletedEventHandler registrarMesaCompleted;
        
        /// <remarks/>
        public event actualizarEstadoReservaCompletedEventHandler actualizarEstadoReservaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarLocales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public beLocal[] listarLocales() {
            object[] results = this.Invoke("listarLocales", new object[0]);
            return ((beLocal[])(results[0]));
        }
        
        /// <remarks/>
        public void listarLocalesAsync() {
            this.listarLocalesAsync(null);
        }
        
        /// <remarks/>
        public void listarLocalesAsync(object userState) {
            if ((this.listarLocalesOperationCompleted == null)) {
                this.listarLocalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarLocalesOperationCompleted);
            }
            this.InvokeAsync("listarLocales", new object[0], this.listarLocalesOperationCompleted, userState);
        }
        
        private void OnlistarLocalesOperationCompleted(object arg) {
            if ((this.listarLocalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarLocalesCompleted(this, new listarLocalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarLocal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string registrarLocal(string nombreLocal, string dirección, int numAforo, int numPisos) {
            object[] results = this.Invoke("registrarLocal", new object[] {
                        nombreLocal,
                        dirección,
                        numAforo,
                        numPisos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registrarLocalAsync(string nombreLocal, string dirección, int numAforo, int numPisos) {
            this.registrarLocalAsync(nombreLocal, dirección, numAforo, numPisos, null);
        }
        
        /// <remarks/>
        public void registrarLocalAsync(string nombreLocal, string dirección, int numAforo, int numPisos, object userState) {
            if ((this.registrarLocalOperationCompleted == null)) {
                this.registrarLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarLocalOperationCompleted);
            }
            this.InvokeAsync("registrarLocal", new object[] {
                        nombreLocal,
                        dirección,
                        numAforo,
                        numPisos}, this.registrarLocalOperationCompleted, userState);
        }
        
        private void OnregistrarLocalOperationCompleted(object arg) {
            if ((this.registrarLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarLocalCompleted(this, new registrarLocalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarMesas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public beMesa[] listarMesas() {
            object[] results = this.Invoke("listarMesas", new object[0]);
            return ((beMesa[])(results[0]));
        }
        
        /// <remarks/>
        public void listarMesasAsync() {
            this.listarMesasAsync(null);
        }
        
        /// <remarks/>
        public void listarMesasAsync(object userState) {
            if ((this.listarMesasOperationCompleted == null)) {
                this.listarMesasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarMesasOperationCompleted);
            }
            this.InvokeAsync("listarMesas", new object[0], this.listarMesasOperationCompleted, userState);
        }
        
        private void OnlistarMesasOperationCompleted(object arg) {
            if ((this.listarMesasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarMesasCompleted(this, new listarMesasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarMesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string registrarMesa(string ubicacion, int numMesa, int numCapacidad) {
            object[] results = this.Invoke("registrarMesa", new object[] {
                        ubicacion,
                        numMesa,
                        numCapacidad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registrarMesaAsync(string ubicacion, int numMesa, int numCapacidad) {
            this.registrarMesaAsync(ubicacion, numMesa, numCapacidad, null);
        }
        
        /// <remarks/>
        public void registrarMesaAsync(string ubicacion, int numMesa, int numCapacidad, object userState) {
            if ((this.registrarMesaOperationCompleted == null)) {
                this.registrarMesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarMesaOperationCompleted);
            }
            this.InvokeAsync("registrarMesa", new object[] {
                        ubicacion,
                        numMesa,
                        numCapacidad}, this.registrarMesaOperationCompleted, userState);
        }
        
        private void OnregistrarMesaOperationCompleted(object arg) {
            if ((this.registrarMesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarMesaCompleted(this, new registrarMesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarEstadoReserva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string actualizarEstadoReserva(int idReserva, int idEstado) {
            object[] results = this.Invoke("actualizarEstadoReserva", new object[] {
                        idReserva,
                        idEstado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarEstadoReservaAsync(int idReserva, int idEstado) {
            this.actualizarEstadoReservaAsync(idReserva, idEstado, null);
        }
        
        /// <remarks/>
        public void actualizarEstadoReservaAsync(int idReserva, int idEstado, object userState) {
            if ((this.actualizarEstadoReservaOperationCompleted == null)) {
                this.actualizarEstadoReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarEstadoReservaOperationCompleted);
            }
            this.InvokeAsync("actualizarEstadoReserva", new object[] {
                        idReserva,
                        idEstado}, this.actualizarEstadoReservaOperationCompleted, userState);
        }
        
        private void OnactualizarEstadoReservaOperationCompleted(object arg) {
            if ((this.actualizarEstadoReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarEstadoReservaCompleted(this, new actualizarEstadoReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class beLocal {
        
        private int idLocalField;
        
        private string nombreLocalField;
        
        private string direccionField;
        
        private int numAforoField;
        
        private int numPisosField;
        
        /// <remarks/>
        public int idLocal {
            get {
                return this.idLocalField;
            }
            set {
                this.idLocalField = value;
            }
        }
        
        /// <remarks/>
        public string nombreLocal {
            get {
                return this.nombreLocalField;
            }
            set {
                this.nombreLocalField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public int numAforo {
            get {
                return this.numAforoField;
            }
            set {
                this.numAforoField = value;
            }
        }
        
        /// <remarks/>
        public int numPisos {
            get {
                return this.numPisosField;
            }
            set {
                this.numPisosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class beMesa {
        
        private string ubicacionField;
        
        private int numMesaField;
        
        private int numCapacidadField;
        
        /// <remarks/>
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <remarks/>
        public int numMesa {
            get {
                return this.numMesaField;
            }
            set {
                this.numMesaField = value;
            }
        }
        
        /// <remarks/>
        public int numCapacidad {
            get {
                return this.numCapacidadField;
            }
            set {
                this.numCapacidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarLocalesCompletedEventHandler(object sender, listarLocalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarLocalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarLocalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public beLocal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((beLocal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarLocalCompletedEventHandler(object sender, registrarLocalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarLocalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarLocalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarMesasCompletedEventHandler(object sender, listarMesasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarMesasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarMesasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public beMesa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((beMesa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarMesaCompletedEventHandler(object sender, registrarMesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarMesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarMesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void actualizarEstadoReservaCompletedEventHandler(object sender, actualizarEstadoReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarEstadoReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarEstadoReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591